\documentclass[12pt]{article}
%\documentclass{scrartcl}
%\setkomafont{disposition}{\normalfont\bfseries}

\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
\geometry{a4paper,
 total={170mm,257mm},
 left=20mm,
 top=20mm,
 bottom=40mm}                   % ... or a4paper or a5paper or ... 
%\geometry{landscape}                % Activate for for rotated page geometry
\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{epstopdf}
\usepackage{float}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}
\usepackage{multicol}



\setlength{\columnsep}{1cm}
\usepackage[backend=bibtex, sorting=none, style=chicago-authordate]{biblatex}
\setlength\bibitemsep{\baselineskip}
\usepackage[british]{babel}
\usepackage[export]{adjustbox}
\usepackage{listings}
\usepackage{color}
\definecolor{codegreen}{rgb}{0,0.6,0}
\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\definecolor{codepurple}{rgb}{0.58,0,0.82}
\definecolor{backcolour}{rgb}{0.95,0.95,0.92}
\lstdefinestyle{mystyle}{
    backgroundcolor=\color{backcolour},
    commentstyle=\color{codegreen},
    keywordstyle=\color{magenta},
    numberstyle=\tiny\color{codegray},
    stringstyle=\color{codepurple},
    basicstyle=\footnotesize,
    breakatwhitespace=false,
    breaklines=true,
    captionpos=b,
    keepspaces=true,
    numbers=left,
    numbersep=5pt,
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    tabsize=2
}

%\usepackage{pdflscape}
\usepackage{textcomp}
\lstset{style=mystyle}


\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
  linkcolor=blue,% hyperlink text will be green
}
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}

%% LOGOS
\usepackage{fancyhdr}
%\setlength{\headheight}{1.5cm}
\addtolength{\headheight}{2cm} % make more space for the header
\pagestyle{fancyplain} % use fancy for all pages except chapter start
\lhead{\includegraphics[height=1.3cm, width=2cm]{../Images/nbislogo.png}} % left logo
\rhead{\includegraphics[height=1.3cm, width=4cm]{../Images/SciLifeLab-logo.jpg}} % right logo
\cfoot{}
\renewcommand{\headrulewidth}{0pt} % remove rule below header

%% DEFINE TOOLS AND VARIABLES
\newcommand{\courseName}{ChIP-seq data analysis}
\newcommand{\coursePoints}{1 hp}
\newcommand{\courseLocation}{Stockholm}
\newcommand{\courseDate}{23-24 November 2017}
\newcommand{\courseLastDay}{24 November 2017}
\newcommand{\courseLeaderA}{Olga Dethlefsen}
\newcommand{\courseEmailA}{olga.dethlefsen@nbis.se}
\newcommand{\courseLeaderB}{Agata Smialowska}
\newcommand{\courseEmailB}{agata.smialowska@nbis.se}
\newcommand{\courseExaminer}{Olga Dethlefsen, PhD}
\newcommand{\affilations}{National Bioinformatics Infrastructure Sweden, Science for Life Laboratory, Stockholm University}

<<loadData, echo=F>>=
file.csv <- "NBIS course application_20171106.csv"
data.csv <- read.csv(file.csv)

# Students names
idx.final <- which(data.csv$Final==1)
data.final <- data.csv[idx.final,]
data.list <- data.frame(Name=data.final$First.Name, Surname=data.final$Last.Name,  email=data.final$Official.e.mail.address)
o <- order(data.list$Name)
data.list <- data.list[o,]
students <- paste(data.list$Name, data.list$Surname, sep=' ')

student <- students[st]
@

\begin{document}

%\cbstart
\large
This is to certify that 


\LARGE
\Sexpr{student}

\large
has successfully taken part in \newline

\LARGE
\begin{center}{\courseName}  \end{center} 


\large
\begin{center} Held in {\courseLocation}, {\courseDate} \end{center} 

\vspace{5mm}
\normalsize
The course consisted of lectures, computer exercises and group discussions. The following subjects and fields were covered in the lectures and exercises:
\begin{itemize}
  \item Quality controls of raw sequencing reads
  \item Reads trimming and filtering
  \item Alignment to the reference genome
  \item Peak-independent quality metrics
  \item Peak calling
  \item Peak-dependent quality metrics and visualization
  \item Differential binding analysis
  \item Common down-stream functional analysis
\end{itemize}


\vspace{5mm}
Examination: Presence during all the lectures and computer/practical exercises

\vspace{5mm}
The course was arranged by the National Bioinformatics Infrastructure Sweden (NBIS) and Science for Life Laboratory (SciLifeLab).

The course is accepted as {\coursePoints} university credits.

\vspace{5mm}
{\courseLocation}, {\courseLastDay}
\vspace{20mm}


{\courseExaminer} \newline
\small
National Bioinformatics Infrastructure Sweden \newline
Science for Life Laboratory \newline
Stockholm University \newline




\end{document}