\documentclass[12pt]{letter}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
\geometry{a6paper, 
 left=15mm,
 top=20mm,
 right=15mm,
 bottom=30mm}                   % ... or a4paper or a5paper or ...
% % %\geometry{landscape}                % Activate for for rotated page geometry


\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{epstopdf}
\usepackage{float}
\usepackage{hyperref}
\usepackage{amssymb}
% \usepackage{dirtree}
% \usepackage{subcaption}
% \usepackage{multicol}
%\setlength{\columnsep}{1cm}
\usepackage[backend=bibtex, sorting=none, style=chicago-authordate]{biblatex}
\setlength\bibitemsep{\baselineskip}
%\usepackage[none]{hyphenat}
\usepackage[british]{babel}
\usepackage[export]{adjustbox}
% \addbibresource{References.bib}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}

\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
  linkcolor=blue,% hyperlink text will be green
  urlcolor=blue
}
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}
%\graphicspath{ {/Users/olga/Documents/BILS/!PROJECTS/2616_zebrafish_mut/Documentation/Images/} }

%% LOGOS
\usepackage{fancyhdr}
%\addtolength{\headheight}{2cm} % make more space for the header
%\addtolength{\footheight}{2cm} % make more space for the header

\pagestyle{fancyplain} % use fancy for all pages except chapter start
%\chead{Epigenomics Data Analysis}
%\lhead{\includegraphics[height=1.3cm, width=2cm]{Logos/NBIS-logo.png}} % left logo
%\rhead{\includegraphics[height=1.3cm, width=4cm]{Logos/SciLifeLab-logo.jpg}} % right logo
\renewcommand{\headrulewidth}{0pt} % remove rule below header

\lfoot{\includegraphics[height=1.3cm, width=2cm]{Logos/NBIS-logo.png}} % left logo
\rfoot{\includegraphics[height=1.3cm, width=4cm]{Logos/SciLifeLab-logo.jpg}} % right logo
%\cfoot{nbis.se}

\begin{document}
<<knitr, echo=FALSE>>=
knitr::opts_chunk$set(echo = TRUE,
size="scriptsize", 
warning = FALSE, 
message = FALSE,
error = TRUE, 
fig.path = "Epi-flyer-figures/",
cache=FALSE)#, 
#cache.path = "../../scratch/cache/3696-report/"
#)
@

% FRONT PAGE
\Large

% Course title
\textbf{Epigenomics Data Analysis}
\normalsize
Short course

% Date and location
\vspace{0.8cm}
\large
\begin{flushright} \textbf{August, 26th - 30th, 2019} % date
\normalsize
Stockholm, SciLifeLab % location
\tiny

% Generic NBIS course description
National course open for PhD students, postdocs, researchers and other employees within Swedish universities.  

% Link to website annoucement
\small
\href{https://www.scilifelab.se/events/epigenomics-data-analysis}{https://www.scilifelab.se/events/epigenomics-data-analysis/}
\end{flushright} 

% Course specific text
\vspace{0.2cm}
\normalsize
%\begin{flushleft}
\centering{
Best practices for data processing and analysis for ChIP-seq, ATAC-seq, Illumina EPIC
arrays, Bisulfite-seq. 
Quality control.
Peak calling. Motif enrichment.
Differential binding, accessibility and
methylation. Functional analyses.
RNA-seq integration. Integrative
visualizations.
}
%\end{flushleft}

% BACK-PAGE
\newpage 
\cfoot{}
% NBIS training events
\Large
\begin{flushleft}
\textbf{NBIS training events}
\newline \normalsize
Up-coming events
\end{flushleft}
\vspace{0.5cm}
\begin{flushleft}


  \footnotesize \textbf{RNA-seq data analysis} \newline \scriptsize
  starts May, 13th, Uppsala
  
  \footnotesize \textbf{Intro. to Bioinformatics using NGS data} \newline \scriptsize
  starts May, 20th, G\"oteborg
  
  \footnotesize \textbf{Biostatistics Essentials} \newline \scriptsize
  starts May, 21st, Uppsala
  
  \footnotesize \textbf{Data integration} \newline \scriptsize
  starts September, 9th, Stockholm
  
  \footnotesize \textbf{Bioinformatics for Principal Investigators} \newline \scriptsize
  starts September, 17th, Stockholm
  
  \footnotesize \textbf{Python programming} \newline \scriptsize
  starts September, 23th, Uppsala
  
  
\vspace{1cm}
More events \& information: \newline
\href{https://nbis.se/training/events.html}{https://nbis.se/training/events.html}

\end{flushleft}





\end{document}  

